### ISSUE TITLE
generate_sixtrack_input error when removing LR from bb_dfs

### ISSUE THREAD

**Issue by skostogl** [lhcopt/lhcmask#31]
Hello,

When the user selects only the HO BB lenses in the bb_dfs dataframe and removes all LR, an error occurs when generating the BEAM expert block in fc.3 (generate_sixtrack_input). Although there are workarounds, the possibility that sxt_df_4d is empty should also be considered. 

Thanks :)

**Comment by giadarol** [comment]
Thanks for opening this issue! Could you please provide an example?

**Comment by skostogl** [comment]
###### Changes in mask

# Prepare bb dataframes
if enable_bb_python:
    bb_dfs = pm.generate_bb_dataframes(mad,
        ip_names=['ip1', 'ip2', 'ip5', 'ip8'],
        harmonic_number=35640,
        numberOfLRPerIRSide=[25, 20, 25, 20],
        bunch_spacing_buckets=10,
        numberOfHOSlices=11,
        bunch_population_ppb=None,
        sigmaz_m=None,
        z_crab_twiss = 0.075,
        remove_dummy_lenses=True)

    # Here the datafremes can be edited, e.g. to set bbb intensity

bb_dfs['b1'] = bb_dfs['b1'][bb_dfs['b1']['label'] == 'bb_ho']
bb_dfs['b2'] = bb_dfs['b2'][bb_dfs['b2']['label'] == 'bb_ho']


###### Error output

KeyError: 'fort3entry'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3565, in _set_item
    loc = self._info_axis.get_loc(key)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'fort3entry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "input.py", line 428, in <module>
    skip_mad_use=True)
  File "/afs/cern.ch/work/s/skostogl/private/workspaces/HL_LHC/DA_CCs_FMA_new/scratch0/w1/sixjobs/mask/templates/pymask/pymasktools.py", line 256, in generate_sixtrack_input
    ]), axis=1)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3040, in __setitem__
    self._set_item(key, value)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3117, in _set_item
    NDFrame._set_item(self, key, value)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3568, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1189, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2714, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2370, in __init__
    super().__init__(values, ndim=ndim, placement=placement)
  File "/home/skostogl/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 130, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 60, placement implies 1

**Comment by giadarol** [comment]
Could you please upload your script so that I can run it? (No need for cleaning it :-)

**Comment by skostogl** [comment]
[test.zip](https://github.com/lhcopt/lhcmask/files/5500735/test.zip)

**Comment by giadarol** [comment]
Solver by PR #32

**Comment by giadarol** [comment]
Solved in release v0.3.1
